apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Apply namespace definitions first
  - namespaces.yaml
  # Apply Elasticsearch next
  - Elasticsearch/
  # Additional services can be added later
  # - Fluent-bit/kustomization.yaml
  # - Kibana/kustomization.yaml
  # - Prometheus/kustomization.yaml
  # - Grafana/kustomization.yaml