apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana-lb
  namespace: flux-system
spec:
  interval: 5m
  releaseName: kibana-lb
  chart:
    spec:
      chart: kibana
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
  values:
    elasticsearch:
      hosts: "https://elasticsearch-master.flux-system:9200"
      existingSecret: "elasticsearch-master-credentials"
      existingSecretUsernameKey: "username"
      existingSecretPasswordKey: "password"
    service:
      type: LoadBalancer
      port: 5601
    ssl:
      verificationMode: certificate
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
