apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- deployment.yaml
- service.yaml

images:
- name: 224072239267.dkr.ecr.us-east-1.amazonaws.com/log-bert-serve
  newTag: v1
