apiVersion: v1
kind: Service
metadata:
  name: log-bert-serve
  labels: { app: log-bert-serve }
spec:
  type: ClusterIP
  selector: { app: log-bert-serve }
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
