apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  interval: 5m
  releaseName: elasticsearch
  chart:
    spec:
      chart: elastic/elasticsearch
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
  values:
    imageTag: "8.5.1"
    replicas: 1
    minimumMasterNodes: 1
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
    persistence:
      enabled: true
    volumeClaimTemplate:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 2Gi
    esJavaOpts: "-Xms512m -Xmx512m"
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
    securityContext:
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
    podSecurityPolicy:
      create: false
    rbac:
      create: false