apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: flux-system
spec:
  interval: 5m
  releaseName: fluent-bit
  chart:
    spec:
      chart: fluent-bit
      version: "0.48.9"
      sourceRef:
        kind: HelmRepository
        name: fluent-helm-charts
        namespace: flux-system
  values:
    rbac:
      create: true
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
    extraVolumes:
      - name: es-certs
        secret:
          secretName: elasticsearch-master-certs
    extraVolumeMounts:
      - name: es-certs
        mountPath: /fluent-bit/es-certs
        readOnly: true
    env:
      - name: ELASTIC_PASSWORD
        valueFrom:
          secretKeyRef:
            name: elasticsearch-master-credentials
            key: password
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack       # Tells Prometheus operator to pick it up
      interval: 10s
      scrapeTimeout: 5s
      additionalEndpoints:
        - port: metrics
          path: /api/v1/metrics/prometheus


    config:
      service: |
        [SERVICE]
            Flush        1
            Log_Level    info
            HTTP_Server  On
            HTTP_Port    2020
      inputs: |
        [INPUT]
            Name              tail
            Path              /var/log/containers/*.log
            Tag               kube.*
            Refresh_Interval 5
      filters: |
        [FILTER]
            Name                kubernetes
            Match               kube.*
            Kube_URL            https://kubernetes.default.svc:443
      outputs: |
        [OUTPUT]
            Name                es
            Match               *
            Host                elasticsearch-master.flux-system
            Port                9200
            Logstash_Format     On
            Replace_Dots        On
            Suppress_Type_Name  On
            Include_Tag_Key     On
            Logstash_Prefix     fluent-bit
            Retry_Limit         False
            tls                 On
            tls.verify          On
            tls.ca_file         /fluent-bit/es-certs/ca.crt
            HTTP_User           elastic
            HTTP_Passwd         ${ELASTIC_PASSWORD}