apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m
  releaseName: grafana
  chart:
    spec:
      chart: grafana
      version: "6.52.1"
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
  values:
    admin:
      user: "admin"
      password: "admin"
    service:
      type: LoadBalancer
      port: 80
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
    env:
      - name: GF_METRICS_ENABLED
        value: "true"
    serviceMonitor:
      enabled: true
      namespace: flux-system
      additionalLabels:
        release: kube-prometheus-stack
      interval: 15s
      scrapeTimeout: 10s
