apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring  # Use the same namespace where Grafana will be deployed
type: Opaque
data:
  admin-user: {{ base64_encode "admin" }}        # e.g., "admin" (base64-encoded)
  admin-password: {{ base64_encode "admin" }}  # your admin password (base64)
