apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: monitoring  # Use the same namespace where Grafana will be deployed
type: Opaque
data:
  admin-user: YWRtaW4=        # e.g., "admin" (base64-encoded)
  admin-password: YWRtaW4=  # your admin password (base64)
