apiVersion: v1
kind: Service
metadata:
  name: log-classifier
  labels: { app: log-classifier }
spec:
  selector: { app: log-classifier }
  ports:
  - name: metrics
    port: 8000
    targetPort: metrics
